feat:update lean_inception.md and imageslean Visao do Produto
fga-eps-mds/2024.2-LIVRO-LIVRE-DOC pull request #39
Opened 2024-11-22 22:51 UTC by guilhermezan42

# Solve Documentação (texto)

## Issues

- Resolve (# numero )

## Descrição

Descrição

## Tipos de mudança

- [ ] Bugfix
- [ ] Melhoria de funcionalidade
- [ ] Nova funcionalidade
- [X] Documentação

## Checklist

- [X] Lint e testes passaram localmente com minhas mudanças
- [] Eu adicionei testes que provam que minha correção é eficaz ou que minha feature funciona
- [] Adicionei informações necessárias na documentação (se precisar)

## Observações adicionais

Nenhuma constatação

2024-11-23 18:06 UTC, matheusyanmonteiro commented
@guilhermezan42  precisa da a descrição detalhada do que você fez
colocar a issue certinha para ter o mapeamento

2024-11-23 18:07 UTC, matheusyanmonteiro commented
https://github.com/fga-eps-mds/2024.2-LIVRO-LIVRE-DOC/issues/7

2024-11-23 18:08 UTC, matheusyanmonteiro commented
![image](https://github.com/user-attachments/assets/f07f47ad-0609-405a-9d78-b5b7192df554)

2024-11-26 23:39 UTC, matheusyanmonteiro submitted a review, later dismissed
LGMT

2024-11-27 00:18 UTC, mateusmaiamaia requested changes
Remover as imagens duplicadas da visão do produto.

2024-11-27 01:18 UTC, guilhermezan42 commented
Removi as imagens repetidas

2024-11-28 17:12 UTC, matheusyanmonteiro approved these changes
LGTM

2024-11-28 17:18 UTC, mateusmaiamaia requested changes
O texto do canvas MVP está na parte do brainstorming, mova o texto pro lugar correto.

2024-12-04 11:03 UTC, mateusmaiamaia approved these changes

2024-12-05 19:11 UTC, merged