feat:update lean_inseption and imagenslean Canvas MVP
fga-eps-mds/2024.2-LIVRO-LIVRE-DOC pull request #41
Opened 2024-11-23 18:50 UTC by oalissonbatista

# Solve Documentação Canvas MVP

## Issues

- Resolve (#14 )

## Descrição

Documentando o Capítulo 10 - Canvas MVP

## Tipos de mudança

- [ ] Bugfix
- [ ] Melhoria de funcionalidade
- [ ] Nova funcionalidade
- [X] Documentação

## Checklist

- [ ] Lint e testes passaram localmente com minhas mudanças
- [ ] Eu adicionei testes que provam que minha correção é eficaz ou que minha feature funciona
- [X] Adicionei informações necessárias na documentação (se precisar)

## Observações adicionais

Nenhuma constatação

2024-11-26 23:38 UTC, matheusyanmonteiro submitted a review, later dismissed
LGMT

2024-11-27 00:05 UTC, mateusmaiamaia commented
A imagem do canvas MVP está errada, fizemos uma nova versão.
Troque a versão da imagem dp canvas MVP

2024-11-27 00:06 UTC, mateusmaiamaia requested changes
Troque a imagem do CAnvas MVP pela versão atualizada.

2024-11-27 22:18 UTC, oalissonbatista commented
Alteração feita @mateusmaiamaia @matheusyanmonteiro.

2024-11-28 17:07 UTC, mateusmaiamaia approved these changes

2024-11-28 17:09 UTC, matheusyanmonteiro approved these changes
LGTM

2024-11-28 17:09 UTC, merged